CHANGELOG.md
README.md
api/lib/mno_enterprise/concerns/mailers/system_notification_mailer.rb
api/spec/mailer/mno_enterprise/system_notification_mailer_spec.rb
core/Gemfile
core/lib/generators/mno_enterprise/install/templates/config/application.yml
core/lib/generators/mno_enterprise/install/templates/config/initializers/mno_enterprise.rb
core/lib/mandrill_client.rb
core/lib/mno_enterprise/core.rb
core/lib/mno_enterprise/mail_adapters/adapter.rb
core/lib/mno_enterprise/mail_adapters/mandrill_adapter.rb
core/lib/mno_enterprise/mail_adapters/sparkpost_adapter.rb
core/lib/mno_enterprise/mail_adapters/test_adapter.rb
core/lib/mno_enterprise/mail_client.rb
core/mno-enterprise-core.gemspec
core/spec/lib/mandrill_client_spec.rb
core/spec/lib/mno_enterprise/mail_adapters/adapter_spec.rb
core/spec/lib/mno_enterprise/mail_adapters/mandrill_adapter_spec.rb
core/spec/lib/mno_enterprise/mail_adapters/sparkpost_adapter_spec.rb
core/spec/lib/mno_enterprise/mail_client_spec.rb
tools/emails/mandrill_utils.rb
tools/emails/sparkpost_utils.rb

Add SparkPost support has a free alternative since:
> All Mandrill users will be required to have a paid monthly MailChimp account by April 27

[MNOE-44] Add SparkPost support

---

core/lib/devise/models/remote_authenticatable.rb

Reopening #18 with correct target branch

fix caching issue

---

core/config/locales/templates/dashboard/organization/en.yml
frontend-admin/src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.coffee
frontend-admin/src/app/components/mnoe-organizations-local-list/mnoe-organizations-local-list.html
frontend-admin/src/app/components/mnoe-users-local-list/mnoe-users-local-list.coffee
frontend-admin/src/app/components/mnoe-users-local-list/mnoe-users-local-list.html
frontend-admin/src/app/index.less
frontend-admin/src/app/views/customers/customers.html
frontend-admin/src/app/views/user/user.html

[Admin] Fix impersonate, on user screen display only user's orgs, switch sections on customer page

---

api/app/views/mno_enterprise/webhook/o_auth/providers/myob.html.haml

MYOB products naming

---

core/lib/devise/models/remote_authenticatable.rb

Backport caching issue fix

---

api/app/views/mno_enterprise/jpi/v1/current_users/show.json.jbuilder
core/app/helpers/mno_enterprise/application_helper.rb

currently only use the gravatar from the user email

add avatar_url to current user

---

frontend-admin/src/app/index.config.coffee

[MNOE-70] Anybody can access /admin/

---

api/spec/controllers/mno_enterprise/webhook/o_auth_controller_spec.rb
common_mnoe_dependencies.rb
frontend/spec/controllers/mno_enterprise/webhook/o_auth_controller_spec.rb

Freeze time when generating JWT as they are time-dependent.

Fix time-dependent specs

---

api/app/assets/javascripts/mno_enterprise/config.js.coffee.erb
core/config/locales/templates/impac/dock/en.yml
core/lib/generators/mno_enterprise/install/templates/config/settings.yml

@ouranos @alexnoox 
This is the PR that contains the i18n file for the Dock and its settings.
https://github.com/maestrano/mno-enterprise-angular/pull/41

Add i18n for dock and its settings

---

api/app/views/mno_enterprise/jpi/v1/app_instances/_resource.json.jbuilder
core/spec/models/mno_enterprise/app_spec.rb

We use snake_case in json views

Fix typo and add missing specs

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
frontend-admin/bower.json
frontend-admin/src/app/components/mno-apps-instances/mno-apps-instances.coffee
frontend-admin/src/app/index.less
frontend-admin/src/app/views/customers/create-step-1/create-step-1.less
frontend-admin/src/app/views/dashboard.layout.html
frontend-admin/src/app/views/organization/organization.html
frontend-admin/src/app/views/user/user.html
frontend/lib/tasks/mnoe_admin_tasks.rake

Admin Panel bug fixes

---

frontend-admin/src/app/views/customers/create-step-2/create-step-2.html

Admin Panel - Only display connectors application in the "Connect your Apps" step of the onboarding.

[MNOE-148] Only display connectors in admin onboarding

---

api/app/views/mno_enterprise/jpi/v1/impac/kpis/_kpi.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb
core/app/models/mno_enterprise/impac/kpi.rb
core/lib/mno_enterprise/testing_support/factories/impac/kpis.rb

This was removed in Maestrano v2.1.0

[MNOE-150] Remove Kpi#name

---

frontend-admin/src/app/views/user.controller.coffee

Admin will be redirected to the original page when exiting impersonation

[MNOE-149] Use redirect_uri when impersonating uri

---

core/lib/her_extension/model/relation.rb
core/spec/lib/her_extension/model/relation_spec.rb

Really simple patch to unwrap filter when creating/initializing.
Specs were a bit harder :)

Fix Her monkey patch #first_or_create/initialize

---

core/app/models/mno_enterprise/impac/dashboard.rb
core/app/models/mno_enterprise/impac/widget.rb

- Remove N+1
- Fix indentation
This fixes #73

[#73] Improve perf for dashboard#organizations

---

frontend/app/assets/stylesheets/mno_enterprise/custom/views/registration.less

https://github.com/maestrano/mno-enterprise-angular/pull/60
@ouranos @alexnoox as we mentioned, I added the corners variable.

Add corners variable to login box

---

api/app/views/mno_enterprise/pages/terms.html.haml
api/config/routes.rb
api/lib/mno_enterprise/concerns/controllers/pages_controller.rb
api/spec/controllers/mno_enterprise/pages_controller_spec.rb
api/spec/routing/mno_enterprise/pages_controller_routing_spec.rb
core/lib/mno_enterprise/core.rb

Reworked #93
Fixed specs and improve cache_key

[MNOE-62] Add Terms page

---

README.md
api/app/jobs/mno_enterprise/event_logger_job.rb
api/lib/mno_enterprise/event_logger.rb
api/spec/jobs/mno_enterprise/event_logger_job_spec.rb

Using ActiveJob, so won't be asynchronous by default but the host app
can use any queue.

Asynchronous Event Logging & improve doc

---

api/lib/mno_enterprise/concerns/controllers/provision_controller.rb
api/spec/controllers/mno_enterprise/provision_controller_spec.rb

Replaces #95 and should work instead of #105 too
@x4d3 FYI

[MNOE-138][MNOE-168] Fix double provisioning issue

---

.travis.yml
api/app/controllers/mno_enterprise/auth/omniauth_callbacks_controller.rb
api/config/initializers/devise.rb
api/config/routes.rb
api/lib/mno_enterprise/event_logger.rb
api/mno-enterprise-api.gemspec
api/spec/controllers/mno_enterprise/auth/omniauth_callback_controller_spec.rb
core/app/models/mno_enterprise/base_resource.rb
core/app/models/mno_enterprise/identity.rb
core/app/models/mno_enterprise/user.rb
core/lib/generators/mno_enterprise/install/templates/config/application.yml
core/lib/mno_enterprise/concerns/controllers/auth/omniauth_callbacks_controller.rb
core/lib/mno_enterprise/concerns/models/app_instance.rb
core/lib/mno_enterprise/testing_support/factories/identity.rb
core/mno-enterprise-core.gemspec
core/spec/models/mno_enterprise/identity_spec.rb
core/spec/models/mno_enterprise/user_spec.rb
rails-template/templates/Gemfile

Add SSO from Intuit, Facebook, Google, LinkedIn
Tested locally. Need to test on UAT.
No specs on OmniAuth::CallbackController yet as I'm struggling with the dynamic routes... :/

[MNOE-167] Add OAuth SSO

---

api/app/views/mno_enterprise/auth/confirmations/new.html.haml

[MNOE-310] Fix empty email error

---

api/app/views/mno_enterprise/provision/_select_organization.html.haml
api/lib/mno_enterprise/concerns/controllers/provision_controller.rb
api/spec/controllers/mno_enterprise/provision_controller_spec.rb
frontend/app/views/mno_enterprise/provision/_select_organization.html.haml

- Display organization list when multiple organization available and
none specified
- Improve permissions check

[MNO-322][MNO-333] Improve App provisioning

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/kpis_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb

@ouranos and/or @cesar-tonnoir please review.

[IMPAC-371] Fix targets & alerts being deleted on metadata currency update

---

README.md
api/config/initializers/health_check.rb
api/mno-enterprise-api.gemspec

- upgrade the health check gem
- better default checks
- improve doc

[MNOE-110] Improve Health Check

---

api/app/views/mno_enterprise/jpi/v1/app_instances/_resource.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/marketplace/_app.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb
core/app/models/mno_enterprise/app.rb

See https://github.com/maestrano/maestrano-hub/pull/153
add multi_instantiable and subcategories to App model.

[MNOE-165] Does not permit to install a second app if the app is not multi_instantiable

---

api/app/views/mno_enterprise/auth/unlocks/_form.html.haml
api/app/views/mno_enterprise/auth/unlocks/new.html.haml

[MNOE-205] Add style to unlock page

---

.travis.yml

Travis: ruby 2.1.8

---

api/app/controllers/mno_enterprise/jpi/v1/app_instances_controller.rb
api/config/routes.rb
api/spec/routing/mno_enterprise/jpi/v1/app_instances_controller_routing_spec.rb
frontend/app/assets/stylesheets/mno_enterprise/variables.less

Added an endpoint to create app_instances (see other pull request on MNOE angular)
Added a couple of css variables missing triggering errors.

[MNOE-170] - Purchase Workflow

---

core/config/locales/templates/dashboard/marketplace/en.yml
core/config/locales/views/webhook/o_auth/providers/en.yml

[MNOE-170] App modals SPA: Locales

---

core/config/locales/templates/dashboard/marketplace/en.yml

Better description when unauthorised to add an app

Locales related to app provsionning fixes

---

README.md

Add documentation on how to extend the backend

---

api/app/views/mno_enterprise/auth/shared/_omniauth.html.haml

Fix SSO links when no providers configured

---

api/app/controllers/mno_enterprise/jpi/v1/admin/invites_controller.rb
api/config/initializers/devise_log.rb
api/lib/mno_enterprise/audit_events_listener.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/app_instances_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/current_users_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/dashboards_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/widgets_controller.rb
api/lib/mno_enterprise/concerns/controllers/pages_controller.rb
api/lib/mno_enterprise/concerns/controllers/provision_controller.rb
api/lib/mno_enterprise/event_logger.rb
api/lib/mno_enterprise/intercom_events_listener.rb
api/spec/controllers/mno_enterprise/jpi/v1/app_instances_controller_spec.rb
api/spec/jobs/mno_enterprise/event_logger_job_spec.rb
api/spec/lib/mno_enterprise/audit_events_listener_spec.rb
api/spec/lib/mno_enterprise/intercom_events_listener_spec.rb
core/app/models/mno_enterprise/impac/dashboard.rb
core/app/models/mno_enterprise/impac/widget.rb
core/app/models/mno_enterprise/user.rb
core/lib/mno_enterprise/concerns/controllers/auth/confirmations_controller.rb
core/lib/mno_enterprise/concerns/controllers/auth/omniauth_callbacks_controller.rb
core/lib/mno_enterprise/concerns/models/app_instance.rb

Delete object (for example widget) could not be found during deserialization in the EventLoggerJob and nil exception were happening.

Fix deserialization error of deleted Object in EventLoggerJob

---

README.md

Update email doc in README

---

core/config/locales/templates/dashboard/en.yml

@BrunoChauvet Please review
Locales for https://github.com/maestrano/mno-enterprise/pull/153 and https://github.com/maestrano/mno-enterprise-angular/pull/93

[MNO-287] Developer Section locales

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/organizations_controller_spec.rb

- Admin not allowed to edit Super Admin
- Last Super Admin cannot drop his role
- Spec the OrganizationController

[MNOE-54][MNO-324] Manage admin role update backend

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/alerts_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/kpis_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/alerts_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb

This is done in Mno-Hub now
@xaun FYI

[MNO-390] Remove calls to kpi_enabled?

---

core/lib/generators/mno_enterprise/install/install_generator.rb
core/lib/generators/mno_enterprise/install/templates/config/newrelic.yml

@hedudelgado & @x4d3 please review

[MNOE-259] Add New Relic config to generator

---

README.md
api/lib/mno_enterprise/intercom_events_listener.rb
core/lib/generators/mno_enterprise/install/templates/config/initializers/mno_enterprise.rb
core/lib/mno_enterprise/concerns/models/intercom_user.rb
core/lib/mno_enterprise/core.rb

Personal Access Tokens have replaced API Keys
See https://developers.intercom.com/docs/personal-access-tokens

[MNOE-162] Add Intercom support for personal token

---

core/lib/generators/mno_enterprise/install/templates/config/settings.yml

Update settings.yml to include impac_pusher_key

---

README.md
UPGRADING.md
api/app/assets/javascripts/mno_enterprise/config.js.coffee.erb
frontend/lib/tasks/mnoe_frontend_tasks.rake
frontend/lib/tasks/templates/package.json

- Use yarn instead of bower to fetch initial package
- Lock packages
- Replace npm by yarn

[MNOE-242] Refactor build process

---

core/mno-enterprise-core.gemspec

1.3 introduces breaking changes

Relax constraint on config gem

---

frontend/lib/tasks/mnoe_frontend_tasks.rake
frontend/lib/tasks/mnoe_locales.rake
frontend/spec/lib/tasks/mnoe_locales_rake_spec.rb

- Fix cp command
- Run it when running frontend:build
Combine #190 & #191 
Thanks @xaun for picking this up.

Fix locales generation

---

api/app/views/mno_enterprise/jpi/v1/admin/users/_user.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/admin/users_controller_spec.rb
frontend-admin/src/app/components/mnoe-api/admin/current-user.svc.coffee
frontend-admin/src/app/components/mnoe-staffs-list/mnoe-staffs-list.html
frontend-admin/src/app/components/mnoe-users-list/mno-users-list.html
frontend-admin/src/app/views/dashboard.controller.coffee
frontend-admin/src/app/views/dashboard.layout.html
frontend-admin/src/app/views/dashboard.less
frontend-admin/src/app/views/staff/create-staff-modal/create-staff.html
frontend-admin/src/app/views/staff/staff.html
frontend-admin/src/app/views/user/user.html

- User table => last logged in (#current_sign_in_at, number of logins (#sign_in_count)
- User menu: display the admin user's name
- Staff page: change the button from “Add a staff” to just “Add staff"
- Change “Name + Surname column titles” to “First name + Last name"

[MNOE-156] - Improvements

---

core/config/locales/templates/dashboard/marketplace/en.yml

[MNOE-286] - Locales from versioning

---

core/config/locales/templates/dashboard/marketplace/en.yml

@ouranos @clemthenem 
Counterpart locales from https://github.com/maestrano/mno-enterprise-angular/pull/148/files

Delete modals locales

---

api/app/views/mno_enterprise/jpi/v1/impac/widgets/_widget.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/widgets_controller.rb
core/app/models/mno_enterprise/impac/widget.rb

**Warning: requires deployment of impac-angular >= 1.5.0-rc3**
Backward-compatible with mnohub
changes approved here: https://github.com/maestrano/mno-enterprise/pull/216

Feature - Rework impac interfaces

---

core/app/assets/stylesheets/mno_enterprise/mail.css

@alexnoox @ouranos Easiest PR ever :)

[MNOE-265] Logo size change

---

rails-template/mnoe-app-template.rb
rails-template/templates/Gemfile

Add the possiblity to choose between the stable or edge version of the
mno-enterprise gem.
stable will point to the latest tagged release (~> 3.0) and edge will
point to the master branch of the github repository.

[Mnoe Template] Ask which mnoe version to use

---

core/lib/generators/mno_enterprise/install/install_generator.rb
core/lib/generators/mno_enterprise/install/templates/config/puma.rb
rails-template/mnoe-app-template.rb

* Add Puma config file
* Allow to use dev version of mnoe

[MNOE-246] Add Puma config file

---

frontend/lib/tasks/mnoe_frontend_tasks.rake

Running the install from the master branch should use edge packages.

Update default packages version

---

frontend/app/assets/stylesheets/mno_enterprise/custom/views/registration.less
frontend/app/views/mno_enterprise/pages/billing_details_required.html.haml

@alexnoox can you review this please?

[MNOE-301] - Refactor billing details page to use the auth design

---

frontend-admin/src/app/components/mnoe-api/admin/current-user.svc.coffee

Admin Panel: Fix logout

---

api/app/views/mno_enterprise/jpi/v1/organizations/_organization.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/organizations_controller.rb
core/config/locales/templates/dashboard/organization/en.yml
core/lib/mno_enterprise/concerns/models/organization.rb
core/lib/mno_enterprise/testing_support/organizations_shared_helpers.rb
core/spec/models/mno_enterprise/organization_spec.rb

Refactor update_billing to use strong_params

[MNOE-375]  Add Payment restrictions

---

core/config/initializers/config.rb

Use settings.yml template as default settings

---

core/app/models/mno_enterprise/user.rb

@alachaum not super happy about this fix but it seems that Her is making the user a singleton in some cases.
@fgourichon that would fix the error at org creation

Fix cache refresh when there's a marshalling error

---

core/lib/generators/mno_enterprise/install/templates/Procfile.dev
frontend/lib/tasks/mnoe_admin_tasks.rake
frontend/lib/tasks/templates-admin/font-faces.less

@ouranos FYI, this is a work in progress.

Admin Panel build

---

core/lib/generators/mno_enterprise/install/templates/config/settings.yml

Adding default value for https://github.com/maestrano/mno-enterprise-angular/pull/174

[MNOE-143] Add marketplace settings

---

core/lib/generators/mno_enterprise/install/templates/config/settings.yml

See https://github.com/maestrano/mnoe-admin-panel/pull/7

Add Admin Panel feature flags

---

core/lib/generators/mno_enterprise/install/install_generator.rb
core/lib/generators/mno_enterprise/install/templates/config/initializers/mno_enterprise.rb
core/lib/mno_enterprise/testing_support/common_rake.rb
rails-template/mnoe-app-template.rb

Rails Template:
- Add SMTP settings
- STDOUT Logging
Install generator:
- Ask questions to fill the initalizer
- Company Name
- Support & System email address
- Remove deprecated options

[MNOE-246] Update Rails template & Install generator

---

api/app/controllers/mno_enterprise/auth/sessions_controller.rb
api/app/controllers/mno_enterprise/webhook/events_controller.rb
api/config/routes.rb
api/lib/mno_enterprise/concerns/controllers/webhook/events_controller.rb

Add endpoint for events webhook

---

core/config/locales/templates/components/en.yml

[MNOE-403] Fix tooltip locale

---

api/app/controllers/mno_enterprise/jpi/v1/admin/audit_events_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/audit_events_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/audit_events/_audit_event.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/audit_events/index.csv.erb
api/app/views/mno_enterprise/jpi/v1/audit_events/_audit_event.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/audit_events/index.json.jbuilder
api/config/routes.rb
api/lib/mno_enterprise/audit_events_listener.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/audit_events_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/audit_events_controller_spec.rb
api/spec/lib/mno_enterprise/audit_events_listener_spec.rb
api/spec/routing/mno_enterprise/jpi/v1/audit_events_controller_routing_spec.rb
core/app/models/mno_enterprise/impac/dashboard.rb
core/app/models/mno_enterprise/org_invite.rb
core/config/initializers/audit_log.rb
core/lib/mno_enterprise/concerns/models/app_instance.rb
core/lib/mno_enterprise/testing_support/factories/audit_event.rb

- (Admin) Export Audit Log to CSV
- Link AuditEvent to Organization when possible
- Audit Log in dashboard
***Requires*** https://github.com/maestrano/maestrano-hub/pull/466

[MNOE-399] Audit Log

---

api/app/controllers/mno_enterprise/jpi/v1/base_resource_controller.rb
api/app/views/mno_enterprise/jpi/v1/current_users/show.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/current_users_controller_spec.rb
core/lib/mno_enterprise/concerns/models/organization.rb

Only not frozen organization should be visible

[MNOE-420] Implement Organization freeze/unfreeze

---

api/lib/mno_enterprise/intercom_events_listener.rb
api/spec/lib/mno_enterprise/intercom_events_listener_spec.rb
core/app/models/mno_enterprise/credit_card.rb
core/lib/mno_enterprise/concerns/models/intercom_user.rb
core/lib/mno_enterprise/concerns/models/organization.rb
core/spec/models/mno_enterprise/credit_card_spec.rb
core/spec/models/mno_enterprise/organization_spec.rb
core/spec/models/mno_enterprise/user_spec.rb
rails-template/files/rubocop.yml
rails-template/mnoe-app-template.rb

Refactor and improve Intercom integration.
* update user data on each event
* Add User custom attributes:
- first name
- last name
- confirmed_at
- admin_role
* Company custom attributes:
- fix CC details
- add CC expiry
- fix App list
- add users count

[MNOE-418] Improve Intercom integration

---

core/config/locales/templates/components/en.yml

@ouranos Locales for https://github.com/maestrano/mno-enterprise-angular/pull/189

[MNOE-401] Locales: Access of user without organizations

---

core/config/locales/templates/components/en.yml

Fix locale

---

core/lib/generators/mno_enterprise/install/install_generator.rb
core/lib/generators/mno_enterprise/install/templates/nginx.conf

Generate a nginx config file for use with Nex!™ and the docker web-ruby
image. This contains caching rules adapted to MNOE.

[MNOE-88] Generate nginx config file

---

api/app/views/mno_enterprise/jpi/v1/admin/organizations/_organization.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/users/show.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/organizations/_organization.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/users_controller_spec.rb
core/lib/mno_enterprise/testing_support/organizations_shared_helpers.rb

Linked to https://github.com/maestrano/mnoe-admin-panel/pull/16

Displays frozen organisations

---

core/config/locales/templates/components/en.yml

Fix no organisation locale

---

api/spec/controllers/mno_enterprise/jpi/v1/audit_events_controller_spec.rb
core/app/models/mno_enterprise/base_resource.rb
core/lib/mno_enterprise/testing_support/mno_enterprise_api_test_helper.rb
core/spec/models/mno_enterprise/base_resource_spec.rb

@cesar-tonnoir @xaun before I merge, could you point to my branch and confirm that this fixes the problem?
The cache will be slightly less efficient but we won't have stale data anymore.

[MNOE-291] Fix association cache bug

---

core/config/locales/templates/onboarding/en.yml

Locales for https://github.com/maestrano/mno-enterprise-angular/pull/204

[MNOE-407] Onboarding locales

---

core/config/locales/templates/onboarding/en.yml

[DEVPL-407] Onboarding locales update

---

api/app/controllers/mno_enterprise/jpi/v1/admin/dashboard_templates_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/dashboard_templates/_dashboard_templates.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/dashboard_templates/index.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/dashboard_templates/show.json.jbuilder
api/config/routes.rb
api/spec/routing/mno_enterprise/jpi/v1/admin/dashboard_templates_controller_rounting_spec.rb
core/app/models/mno_enterprise/impac/dashboard.rb

- Add controller
- Add index and destroy
- Add tests
- Update routes
- Add views

[MNOE-447] Add admin dashboard templates:

---

core/config/locales/templates/components/en.yml

[MNOE-407] Onboarding: fix missing locale

---

api/app/controllers/mno_enterprise/impersonate_controller.rb
api/spec/controllers/mno_enterprise/impersonate_controller_spec.rb

[MNOE-307] - Impersonate with the right organization

---

frontend/lib/tasks/mnoe_locales.rake

Impac! i18n

---

api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb
core/lib/mno_enterprise/concerns/models/ability.rb

@cesar-tonnoir need to do specs, just putting there here for FYI & please review
https://github.com/maestrano/impac-angular/pull/358

[IMPAC-598] Extend manage_kpi ability for widget kpis

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/widgets_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/organizations_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/teams_controller.rb
api/lib/mno_enterprise/concerns/controllers/webhook/o_auth_controller.rb
api/lib/mno_enterprise/event_logger.rb
core/app/models/mno_enterprise/impac/widget.rb
core/config/initializers/audit_log.rb
core/lib/mno_enterprise/concerns/controllers/auth/registrations_controller.rb
core/lib/mno_enterprise/concerns/models/team.rb

[MNOE-426] - Logged additional events

---

core/config/locales/templates/components/en.yml
core/config/locales/templates/onboarding/en.yml

@alexnoox 
Locales added to match mnoe-enterprise-angular changes

[MNOE-501] Locales added for on-boarding improvement

---

frontend/lib/tasks/mnoe_admin_tasks.rake
frontend/lib/tasks/mnoe_frontend_tasks.rake

Default variables: builds rename original variables.less to variables-default.less

---

api/app/controllers/mno_enterprise/jpi/v1/admin/theme_controller.rb
core/lib/mno_enterprise/core.rb
core/lib/mno_enterprise/platform_adapters/adapter.rb
core/lib/mno_enterprise/platform_adapters/local_adapter.rb
core/lib/mno_enterprise/platform_adapters/nex_adapter.rb
core/lib/mno_enterprise/system_manager.rb
core/mno-enterprise-core.gemspec
core/spec/lib/mno_enterprise/platform_adapters/nex_adapter_spec.rb
frontend/lib/tasks/mnoe_admin_tasks.rake
frontend/lib/tasks/mnoe_frontend_tasks.rake

* Nex!™ adapter for assets sync
* Update Theme Previewer to publish assets
**TODO**
* Nex!™ adapter:
* Implement restart
* Implement SSL management
* The ThemeController was not spec'd

[MNOE-452] Nex!™ Adapter & Assets sync

---

api/app/controllers/mno_enterprise/jpi/v1/admin/tenants_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/tenants/show.json.jbuilder
api/config/routes.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/tenants_controller_spec.rb
api/spec/routing/mno_enterprise/jpi/v1/admin/tenants_controller_routing_spec.rb
core/lib/mno_enterprise/platform_adapters/adapter.rb
core/lib/mno_enterprise/platform_adapters/local_adapter.rb
core/lib/mno_enterprise/platform_adapters/nex_adapter.rb
core/lib/mno_enterprise/platform_adapters/test_adapter.rb
core/lib/mno_enterprise/system_manager.rb
core/lib/mno_enterprise/testing_support/factories/tenant.rb
core/lib/mno_enterprise/testing_support/shared_examples/platform_adapter.rb
core/spec/lib/mno_enterprise/platform_adapters/local_adapter_spec.rb
core/spec/lib/mno_enterprise/platform_adapters/nex_adapter_spec.rb
core/spec/lib/mno_enterprise/system_manager_spec.rb
core/spec/models/mno_enterprise/tenant_spec.rb
core/spec/rails_helper.rb

[MNOE-448] Add DNS/SSL Management

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/base_resource/_member.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/app_instances_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/app_instances_controller_spec.rb
core/app/models/mno_enterprise/user.rb

@ouranos for review, @x4d3 for info

Fix/simple fixes + fix spec

---

core/config/locales/templates/impac/dock/en.yml
core/config/locales/templates/onboarding/en.yml

https://github.com/maestrano/mno-enterprise-angular/pull/247

[MNOE-499] Add locales

---

api/app/controllers/mno_enterprise/jpi/v1/admin/invites_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/app_answers_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/invites_controller_spec.rb

[MNOE-538] Admin Panel - Error when inviting existing user

---

api/app/controllers/mno_enterprise/jpi/v1/admin/app_feedbacks_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/app_questions_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/app_feedbacks/_comment.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/app_feedbacks/_resource.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/app_feedbacks/index.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/app_questions/_answer.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/app_questions/_resource.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/app_questions/index.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/base_resource/_app_review.json.jbuilder
api/config/routes.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/app_feedbacks_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/app_questions_controller_spec.rb
api/spec/routing/mno_enterprise/jpi/v1/admin/app_feedbacks_controller_routing_spec.rb
api/spec/routing/mno_enterprise/jpi/v1/admin/app_questions_controller_routing_spec.rb

@ouranos Added endpoints so that I was able to group reviews/comments and questions/answers together.

[MNOE-474] Add endpoints to admin api

---

core/config/locales/templates/dashboard/marketplace/en.yml

[MNOE-474] Fix locale typo

---

frontend/lib/tasks/mnoe_locales.rake
frontend/spec/lib/tasks/mnoe_locales_rake_spec.rb

Fix build for versions < 1.5.0-rc8

Fix impac locales task

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/teams_controller.rb

Hey @ouranos ,
Adding Jira link since Jira did not get the PR
https://maestrano.atlassian.net/browse/MNOE-533

[MNOE-533] Reload her team object and fix fetch teams

---

api/app/views/mno_enterprise/jpi/v1/app_feedbacks/_resource.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/app_questions/_resource.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/app_feedbacks_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/app_questions_controller_spec.rb

@ouranos This should take care of the issue regarding rejected comments being included in the response when fetching reviews. Please review.

[MNOE-558] Filter out rejected comments from feedbacks

---

core/config/locales/templates/dashboard/organization/en.yml

Locales for https://github.com/maestrano/mno-enterprise-angular/pull/276

[PF-164] Explain roles in invite modal

---

core/config/locales/templates/components/en.yml
core/config/locales/templates/dashboard/en.yml

@x4d3 @hedudelgado please review

[MNOE-551] Add tasks feature locales for mnoe-ng

---

frontend/lib/tasks/mnoe_admin_tasks.rake

Inject impac-angular dependency locked on the yarn.lock version
Used for the dashboard designer
If not dependency is found, it won't inject the resolution (eg: for older version)

Admin build: inject impac-angular dependency

---

api/spec/controllers/mno_enterprise/config_controller_spec.rb

Simple spec to cover the `ConfigController`
Let me know if you think there's a better way

Add missing ConfigController specs

---

api/app/views/mno_enterprise/pages/loading.html.erb
frontend/app/assets/templates/mno_enterprise/maestrano-components/loading_lounge.html

See #298
This part was missing

[MNOE-643] Add white logo on App loading page

---

api/app/controllers/mno_enterprise/jpi/v1/admin/app_metrics_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/app_metrics/_app_metrics.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/app_metrics/index.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/app_metrics/show.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/organizations/_organization.json.jbuilder
api/config/routes.rb
api/spec/routing/mno_enterprise/jpi/v1/admin/app_metrics_controller_routing_spec.rb
api/spec/routing/mno_enterprise/jpi/v1/admin/users_controller_routing_spec.rb
core/app/models/mno_enterprise/app_metrics.rb
core/lib/mno_enterprise/concerns/models/organization.rb

[MNOE-479] - Add additional analytics

---

frontend/lib/mno_enterprise/frontend/locales_generator.rb

[I18n] Fix generation

---

api/app/controllers/mno_enterprise/jpi/v1/admin/assets_controller.rb
api/config/routes.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/products_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/assets_controller_spec.rb
core/app/models/mno_enterprise/asset.rb
core/lib/mno_enterprise/testing_support/factories/asset.rb

Add assets endpoint to upload local product screenshots.
I haven't tested it live as it's a pain to do so with postman/curl. Will be easier to test directly with your frontend.

Expose assets on admin API

---

api/app/controllers/mno_enterprise/jpi/v1/admin/assets_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/products/_product.json.jbuilder

[MNOE-492] Add assets in product view

---

api/spec/controllers/mno_enterprise/jpi/v1/admin/products_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/products_controller_spec.rb

[MNOE-492] Fix products specs

---

api/app/views/mno_enterprise/jpi/v1/products/_product.json.jbuilder
core/app/models/mno_enterprise/product.rb

Goes with https://github.com/maestrano/maestrano-hub/pull/650

[MNOE-492] - 4.0 local products free trial

---

api/app/controllers/mno_enterprise/jpi/v1/admin/product_markups_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/product_markups/_product_markup.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/product_markups/index.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/product_markups/show.json.jbuilder
api/config/routes.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/products_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/product_markups_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/products_controller_spec.rb
core/app/models/mno_enterprise/base_resource.rb
core/app/models/mno_enterprise/product_markup.rb
core/lib/mno_enterprise/testing_support/factories/product_markup.rb

[MNOE-476] - Markup screens

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/sub_tenants_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/sub_tenants/_sub_tenant.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/sub_tenants/index.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/sub_tenants/show.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/users/_user.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/users/show.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/current_users/show.json.jbuilder
api/config/routes.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/sub_tenants_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/users_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/current_users_controller_spec.rb
core/app/models/mno_enterprise/sub_tenant.rb
core/app/models/mno_enterprise/user.rb
core/lib/mno_enterprise/concerns/models/ability.rb
core/lib/mno_enterprise/testing_support/factories/sub_tenants.rb
core/lib/mno_enterprise/testing_support/factories/users.rb

[MNOE-483] Add Sub Tenant Feature

---

api/app/controllers/mno_enterprise/jpi/v1/admin/apps_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/apps/_app.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/apps/index.json.jbuilder
api/config/routes.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/apps_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/apps_controller_spec.rb
api/spec/routing/mno_enterprise/jpi/v1/admin/apps_controller_routing_spec.rb
core/app/models/mno_enterprise/app.rb
core/spec/models/mno_enterprise/app_spec.rb

* Add App Catalogue management
* Fix marketplace caching to expire when removing app from catalogue

Add App Catalogue management

---

core/app/helpers/mno_enterprise/impersonate_helper.rb
core/config/initializers/audit_log.rb

As per QA bug - @ouranos for review

[FIX] - Added impersonation in audit log

---

api/app/controllers/mno_enterprise/jpi/v1/base_resource_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb
core/app/models/mno_enterprise/tenant_config.rb
core/config/initializers/00_tenant_config_schema.rb
core/spec/models/mno_enterprise/tenant_config_spec.rb

* Fix marketplace crash when empty
* Update app list selection for public pages

[MNOE-598] App Selection Screen Fixes

---

api/app/controllers/mno_enterprise/jpi/v1/admin/invoices_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/invoices_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/users_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/subscriptions_controller_spec.rb
core/lib/mno_enterprise/testing_support/factories/arrears_situation.rb
core/lib/mno_enterprise/testing_support/factories/users.rb
core/lib/mno_enterprise/testing_support/mno_enterprise_api_test_helper.rb

Add sub-tenant scoping on invoices, users and organizations.
Also re-written specs for the related controllers.

Account Manager (Sub-Tenant) scoping

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscriptions_controller.rb

Add search capability on subscriptions

Add search capability

---

core/config/initializers/00_tenant_config_schema.rb

Allowing null if Intercom config is not set

Allow null for intercom config

---

core/config/locales/templates/dashboard/organization/en.yml
core/config/locales/templates/dashboard/teams/en.yml

[MNOE-597][WIP] Missing Conversion

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/current_users_controller.rb
api/spec/requests/devise/registration_spec.rb
core/app/models/mno_enterprise/base_resource.rb
core/app/models/mno_enterprise/user.rb
core/lib/mno_enterprise/testing_support/factories/users.rb
core/spec/lib/devise/model/remote_authenticable_spec.rb
core/spec/models/mno_enterprise/user_spec.rb

Replaces #342 
* confirmation email not sent
* password change

[MNOE-510][MNOE-612] Fix devise regression

---

core/config/locales/templates/components/en.yml

@ouranos updated locales for new language selectbox locales in mnoe-ng

[MNOE-597] Language Selectbox Locales

---

core/app/models/mno_enterprise/impac/dashboard.rb
core/spec/models/mno_enterprise/impac/dashboard_spec.rb

- [EMERALD-37] Fix organizations returned as data_sources for templates

Fixes - Dashboard templates

---

api/app/controllers/mno_enterprise/jpi/v1/admin/notifications_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/tasks_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/notifications_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/tasks_controller_spec.rb

@BrunoChauvet fyi
build OK: https://travis-ci.org/cesar-tonnoir/mno-enterprise/builds/275356738

Fix tasks owner_id

---

core/config/locales/templates/components/en.yml

Transcript of https://github.com/maestrano/mno-enterprise-angular/blob/feature/tasks/src/locales/en.locale.json#L572

Add missing locales

---

api/app/views/mno_enterprise/auth/sessions/_form.html.haml
core/config/locales/templates/dashboard/provisioning/en.yml
core/config/locales/templates/impac/dock/en.yml
core/config/locales/views/auth/sessions/en.yml

@ouranos Updated locales and sign in page. Please review.

[MNOE-597][Bug] Missing Conversion

---

core/config/locales/templates/impac/dock/en.yml

@ouranos @BrunoChauvet Updates missing locale for app settings modal. Please review.

[BUG] Missing locale

---

api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb

@BrunoChauvet This should alleviate the issue of duplicate users being returned on the admin panel when using the search feature. Please review. (Leaving additional comments in JIRA)

[BUG] Update controller to remove duplicate search results

---

core/app/views/system_notifications/task-notification.html.erb
core/app/views/system_notifications/task-notification.text.erb

@x4d3 @BrunoChauvet In the emails, it shows the date with the time attached. This should take care of the issue so that only the date shows. Please review.

[BUG] tasks emails

---

core/lib/html_processor.rb
core/spec/lib/html_processor_spec.rb

Correctly sanitize the app's description

[DEVPL-157] Video player on an app's description

---

core/config/locales/templates/dashboard/marketplace/en.yml

@ouranos Updated locales as part of bug fix 👍

[MNOE-587][Bug] Nan average rating

---

api/app/controllers/mno_enterprise/jpi/v1/admin/tasks_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/tasks_controller.rb
api/lib/mno_enterprise/concerns/mailers/system_notification_mailer.rb
api/spec/mailer/mno_enterprise/system_notification_mailer_spec.rb
core/app/views/system_notifications/task-notification.html.erb
core/app/views/system_notifications/task-notification.text.erb
core/lib/mno_enterprise/smtp_client.rb

- make subject an option of deliver in SmtpClient
- Add inbox link in email
- Remove The display of due date when there is no Due date

Improve Email format

---

api/app/controllers/mno_enterprise/jpi/v1/admin/invoices_controller.rb
api/lib/mno_enterprise/concerns/mailers/system_notification_mailer.rb
api/spec/mailer/mno_enterprise/system_notification_mailer_spec.rb
api/spec/rails_helper.rb
core/app/views/system_notifications/invoice.html.erb
core/lib/mno_enterprise/mail_adapters/mandrill_adapter.rb
core/lib/mno_enterprise/smtp_client.rb
core/spec/lib/mno_enterprise/mail_adapters/mandrill_adapter_spec.rb
core/spec/lib/mno_enterprise/smtp_client_spec.rb

Replace #465 & fixes #456 
* Fix controller code
* Add attachment support to Mandrill (Sparkpost does not support using dynamic attachments with templates)
* Add SystemNotificationMailer specs
* Add SmtpClient specs

[MNOE-602] Invoice Email Fixes

---

core/app/models/mno_enterprise/tenant_config.rb
core/config/initializers/00_tenant_config_schema.rb
core/lib/mno_enterprise/core.rb
core/spec/models/mno_enterprise/tenant_config_spec.rb

- Fix Array default
- Fix JSON Schema

Fix TenantConfig Array default handling

---

api/app/controllers/mno_enterprise/jpi/v1/admin/theme_controller.rb

No specs as the `ThemeController` is currently not spec'd :scream: 
I've created a JIRA to take care of it next week.

[MNOE-695] Theme previewer: reset to default

---

core/config/initializers/00_tenant_config_schema.rb

Fix bug with the unsaved changes notification

[MNOE-693] Fix JSON schema

---

core/app/helpers/mno_enterprise/image_helper.rb
core/app/pdf/mno_enterprise/invoice_pdf.rb
core/app/views/system_notifications/confirmation-instructions.html.erb
core/app/views/system_notifications/delete-request-instructions.html.erb
core/app/views/system_notifications/email-change.html.erb
core/app/views/system_notifications/organization-invite-existing-user.html.erb
core/app/views/system_notifications/organization-invite-new-user.html.erb
core/app/views/system_notifications/password-change.html.erb
core/app/views/system_notifications/reconfirmation-instructions.html.erb
core/app/views/system_notifications/registration-instructions.html.erb
core/app/views/system_notifications/reset-password-instructions.html.erb
core/app/views/system_notifications/unlock-instructions.html.erb
core/lib/mno_enterprise/smtp_client.rb
core/spec/helpers/image_helper_spec.rb

@ouranos 
- Rebase on 3.3
- Update syntax
- Remove doubles quotes
- Add spec

[MNOE-563][MNOE-677] Add main_logo_white_bg on notifications and fix size

---

api/app/controllers/mno_enterprise/impersonate_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/base_resource/_member.json.jbuilder
api/spec/controllers/mno_enterprise/impersonate_controller_spec.rb

[MNOE-699][MNOE-658] Disallow Staff impersonation

---

api/app/controllers/mno_enterprise/config_controller.rb
api/spec/controllers/mno_enterprise/config_controller_spec.rb

Only return the default locale when I18n is disabled

[MNOE-417] Fix available locales bug

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/subscriptions_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/subscriptions_controller_spec.rb

Support update of Subscription pricing and contract

[MNOE-712] Fix editing subscription pricing

---

core/app/views/system_notifications/invoice.html.erb
core/app/views/system_notifications/invoice.text.erb

Price in invoice was displayed as cents

[MNOE-707] - Fix price display

---

api/spec/controllers/mno_enterprise/jpi/v1/impac/dashboards_controller_spec.rb

Temporarily disable dashboards_controller_spec tests

---

core/config/locales/templates/dashboard/provisioning/en.yml

Aligned with https://github.com/maestrano/mno-enterprise-angular/pull/371

[MNOE-750] Add locale for json root element

---

core/app/pdf/mno_enterprise/invoice_pdf.rb

The invoice will mention 'The charges will appear as INV # on your bank statement' in the end of the Summary section

[PF-183] Invoice template: add bank statement mention

---

api/app/views/mno_enterprise/jpi/v1/organizations/_organization.json.jbuilder
core/lib/mno_enterprise/testing_support/organizations_shared_helpers.rb

Add organization billing_currency to organization view to simplify querying from mnoe-angular

[MNOE-780] - Add billing_currency in org view

---

core/app/models/mno_enterprise/tenant_config.rb
core/app/models/mno_enterprise/user.rb
core/lib/mno_enterprise/engine.rb
core/spec/models/mno_enterprise/user_spec.rb

* Revert #571 as it was introducing a regression
* Fix the original issue properly

[MNOE-783] Fix registration route not being loaded

---

api/app/assets/javascripts/mno_enterprise/config.js.coffee.erb
api/app/controllers/devise/password_expired_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/app_instances_sync_controller.rb
api/app/views/devise/password_expired/show.html.haml
api/app/views/mno_enterprise/auth/confirmations/_form.html.haml
api/config/initializers/devise.rb
core/app/controllers/mno_enterprise/application_controller.rb
core/config/locales/templates/components/en.yml
core/lib/devise/controllers/extension_helpers.rb

Improve devise default configuration
* Enable account lockout
* Expose devise configuration to the frontend (for password length check)
* Fix password expiry
* Fixed session timeout

[MNOE-209][MNOE-788] Improve Devise configuration

---

api/app/views/mno_enterprise/jpi/v1/admin/users/_user.json.jbuilder

[MNOE-791] Add locked_at & access_locked? to the user API

---

core/config/initializers/00_tenant_config_schema.rb

@ouranos Leaving comments in JIRA, please review :)

Add impac dashboard feature flag to frontend config settings

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
core/lib/mno_enterprise/concerns/controllers/auth/omniauth_callbacks_controller.rb

provision_app_instances! missing bang.. bug & specs fixed
@ouranos (unable to add a reviewer)

[MNOE-799] Unable to create new customer from Admin Panel

---

api/config/routes.rb
api/spec/routing/mno_enterprise/jpi/v1/admin/product_markups_controller_routing_spec.rb
core/config/initializers/00_tenant_config_schema.rb

Add feature flag and missing routing specs

[MNOE-809] Add a feature flag for Product Markup

---

core/config/locales/templates/components/en.yml

[MNOE-793] Title i18n

---

api/lib/mno_enterprise/csv_importer.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb

- sub_tenant was not loaded, triggering a 404 when api/app/views/mno_enterprise/jpi/v1/admin/users/_user.json.jbuilder was called

[OPAL-261] Fix upload issue

---

rails-template/templates/Gemfile

This is to avoid issue with containers

[MNO-712] Update minimum NewRelic version

---

api/app/controllers/mno_enterprise/jpi/v1/app_instances_sync_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/app_instances_sync_controller_spec.rb
core/lib/mno_enterprise/concerns/models/organization.rb

The (trigger_)app_instance_sync will also return has_running_cube
for a awared 'Real-time syncing' on Impac-Angular
Depends on https://github.com/maestrano/maestrano-hub/pull/802

[IMPAC-665] Sync status on impac dashboard

---

api/app/controllers/mno_enterprise/jpi/v1/app_instances_sync_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/app_instances_sync_controller_spec.rb

The property `has_running_cubes` does not seem to exist any more on the MNOE API
https://github.com/maestrano/maestrano-hub/blob/develop/app/resources/api/mnoe/v2/organization_resource.rb

[MNOE-837] Check running cubes using MNOE API

---

api/lib/mno_enterprise/concerns/mailers/system_notification_mailer.rb
api/spec/mailer/mno_enterprise/system_notification_mailer_spec.rb

Add field for task email

---

api/app/assets/javascripts/mno_enterprise/error_page.js
api/app/views/mno_enterprise/application/error_page.html.haml
api/config/initializers/assets.rb
api/config/routes.rb
api/lib/mno_enterprise/api/engine.rb
api/lib/mno_enterprise/concerns/controllers/pages_controller.rb
api/spec/controllers/mno_enterprise/pages_controller_spec.rb
api/spec/routing/mno_enterprise/pages_controller_routing_spec.rb
core/app/controllers/mno_enterprise/application_controller.rb
core/config/locales/views/errors/en.yml
core/spec/controllers/mno_enterprise/application_controller_spec.rb
frontend/app/assets/stylesheets/mno_enterprise/error-page.less
frontend/app/assets/stylesheets/mno_enterprise/main.less
frontend/app/assets/stylesheets/mno_enterprise/variables.less
frontend/app/views/layouts/mno_enterprise/public.html.haml
frontend/spec/controllers/mno_enterprise/pages_controller_spec.rb

Better handle when maestrano-hub is down or slow to respond.
We rescue Faraday errors and return an appropriate error code:
* 503 Service Unavailable when maestrano-hub is down
* 429 Too Many Request on connection timeout

[MNOE-110] Handle MnoHub Errors

---

api/app/controllers/mno_enterprise/jpi/v1/admin/theme_controller.rb

[MNOE-838] Refactor theme ctrl to rebuild previewer style after publish

---

core/lib/generators/mno_enterprise/install/templates/config/settings.yml

[MNOE-823] Fix alphabetical order

---

api/app/controllers/mno_enterprise/jpi/v1/admin/app_metrics_controller.rb

Depends on https://github.com/maestrano/maestrano-hub/pull/826

[MNOE-749] - Enable filter by terms on app_metrics

---

api/app/views/mno_enterprise/webhook/o_auth/authorize.html.haml
core/app/helpers/mno_enterprise/image_helper.rb
core/app/views/system_notifications/confirmation-instructions.html.erb
core/app/views/system_notifications/delete-request-instructions.html.erb
core/app/views/system_notifications/email-change.html.erb
core/app/views/system_notifications/organization-invite-existing-user.html.erb
core/app/views/system_notifications/organization-invite-new-user.html.erb
core/app/views/system_notifications/password-change.html.erb
core/app/views/system_notifications/reconfirmation-instructions.html.erb
core/app/views/system_notifications/registration-instructions.html.erb
core/app/views/system_notifications/reset-password-instructions.html.erb
core/app/views/system_notifications/unlock-instructions.html.erb
core/mno-enterprise-core.gemspec
core/spec/helpers/image_helper_spec.rb

html max-height and max-width are not recognised by some mail clients like Outlook, so we calculate them ourselves

[MNOE-807] Set max heights for images

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/tenant_invoices_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/organizations/index.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb

* Use `#fetch` to avoid duplicate requests
* Remove `credit_cards` from `/organizations` to avoid N+1
See commits log for more details

[MNOE-827] Improve admin endpoints performances

---

api/app/views/mno_enterprise/jpi/v1/admin/products/_product.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/products_controller.rb
core/app/models/mno_enterprise/base_resource.rb

- Ability to fetch only a set of fields in base_resource
- Ability to skip fetching all dependencies for products

[MNOE-806] Ability to skip depedencies for products

---

frontend/lib/tasks/mnoe_admin_tasks.rake
frontend/lib/tasks/mnoe_frontend_tasks.rake

[MNOE-805] Better default logo logic

---

api/lib/mno_enterprise/concerns/controllers/pages_controller.rb
api/spec/controllers/mno_enterprise/pages_controller_spec.rb
core/lib/mno_enterprise/concerns/models/app_instance.rb
core/lib/mno_enterprise/testing_support/factories/app_instances.rb
core/spec/models/mno_enterprise/app_instance_spec.rb

* Add `AppInstance#running?`
* Includes `app` to be able to get the logo
* Add `durations` to specs (added in MnoHub with maestrano/maestrano-hub#899)
* Add non-regression specs

[MNOE-928] Loading lounge fix

---

api/app/views/mno_enterprise/jpi/v1/admin/users/_user.json.jbuilder
core/app/models/mno_enterprise/user.rb

Added several attributes that our frontend needed for the PR.

[MNOE-907] Improve user info

---

api/spec/controllers/mno_enterprise/pages_controller_spec.rb

[MNOE-928] Add specs

---

api/app/assets/javascripts/mno_enterprise/config.js.coffee.erb
api/app/views/mno_enterprise/auth/sessions/new.html.haml
core/config/locales/views/auth/sessions/en.yml

Allows the frontend to warn the user when he will get logged off due to inactivity
Continued https://github.com/maestrano/mno-enterprise/pull/632 in this PR

[MNOE-872] Expose session timeout config

---

api/app/controllers/mno_enterprise/jpi/v1/admin/impac/widgets_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/impac/widgets/_widget.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/impac/widgets/_widget.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/widgets_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/impac/widgets_controller_spec.rb
core/app/models/mno_enterprise/impac/widget.rb

@ouranos @cesar-tonnoir please review and see corresponding changes in MnoHub: https://github.com/maestrano/maestrano-hub/pull/915
@ouranos apparently there is a v2 migration? Do I need to do something for that? Thanks

[IMPAC-793] Add layouts attribute to Widget

---

api/config/initializers/devise.rb
api/mno-enterprise-api.gemspec
rails-template/mnoe-app-template.rb

* Upgrade gem and config to use new version of the Graph API
* Also update omniauth-google

 [MNO-784] Fix facebook SSO

---

api/app/views/mno_enterprise/jpi/v1/marketplace/_app.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb
core/lib/mno_enterprise/testing_support/factories/apps.rb

@ouranos in tandem with https://github.com/maestrano/maestrano-hub/pull/910

[APPINT-1161][MNOE-920] Add sso_enabled

---

CHANGELOG.md
README.md
UPGRADING.md
docs/README.md
docs/feature-flags.md
docs/testing.md

Still WIP but opening it as it might be useful
@x4d3 FYI

Add v2 doc - Feature flags

---

core/config/locales/templates/dashboard/marketplace/en.yml

[MNOE-962] One-off locale

---

rails-template/mnoe-app-template.rb

Adding this to the application config template so it's explicit in the
host project.

Use Redis for cache if present

---

api/app/controllers/mno_enterprise/jpi/v1/admin/product_markups_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/product_markups/_product_markup.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/marketplace/index.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/product_markups_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb

Covers JIRA issues:
- MNOE-973
- MNOE-888
- MNOE-1043

[MNOE-973][MNOE-888] ProductMarkup: json response updated

---

core/config/locales/templates/dashboard/provisioning/en.yml

Added front-end relevant provisioning subscriptions' locales

[MNOE-1095] Added new subscription provisioning locales

---

core/app/pdf/mno_enterprise/invoice_pdf.rb
core/config/initializers/00_tenant_config_schema.rb
core/config/locales/pdf/en.yml

- Add new fields to tenant frontend configuration for invoice contact
details and payment information.
- Update invoice pdf generation to display contact details and payment
info

[MNOE-1084] Extend invoice metadata

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscription_events_controller.rb

[MNOE-1121] Scope SubscriptionEvents to AccountManager

---

api/app/views/mno_enterprise/jpi/v1/admin/subscription_events/_subscription_event.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/subscription_events/_subscription_event.json.jbuilder
core/lib/mno_enterprise/testing_support/factories/subscription_event.rb

[MNOE-1089] Subscriptions events - Capture and display the user

---

core/config/initializers/00_tenant_config_schema.rb

Fix default value to be a boolean and not a string

[MNOE-1155] Fix config schema

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscription_events_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscriptions_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/subscriptions_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/subscription_events_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/subscriptions_controller_spec.rb
core/app/models/mno_enterprise/audit_event.rb
core/app/models/mno_enterprise/base_resource.rb
core/app/models/mno_enterprise/subscription.rb
core/app/models/mno_enterprise/subscription_event.rb
core/config/initializers/audit_log.rb
core/lib/mno_enterprise/testing_support/mno_enterprise_api_test_helper.rb
core/spec/models/mno_enterprise/base_resource_spec.rb
core/spec/models/mno_enterprise/subscription_event_spec.rb
core/spec/models/mno_enterprise/subscription_spec.rb

[MNOE-1134] Organization name & description not appearing in Audit Log for subscription

---

api/app/views/mno_enterprise/jpi/v1/admin/subscriptions/_subscription.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/subscriptions/_subscription.json.jbuilder
core/config/locales/templates/dashboard/provisioning/en.yml

Needed after we save subscription to have the billing information after we save the subscription on the confirm page.

[MNOE-1164] Add billing information to subscription partial

---

api/app/views/mno_enterprise/jpi/v1/teams/_team.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/products_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/teams_controller.rb
core/lib/mno_enterprise/concerns/models/ability.rb

Update products controller to send organization_id in params when
fetching single product.

[MNOE-1203][MNOE-1014] Product markups & team apps

---

api/app/views/mno_enterprise/jpi/v1/admin/teams/_team.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/teams/_team.json.jbuilder

- Add guarding to team partial views in the event that apps are not
included in the request
- Remove unnecessary guarding from admin team partial

[MNOE-1259] 500 when adding team member

---

api/app/controllers/mno_enterprise/jpi/v2/kpis_controller.rb
api/config/routes.rb
api/spec/controllers/mno_enterprise/jpi/v2/kpis_controller_spec.rb

- include the route and controller for Kpi in jpi/v2

[MARLIN-233] KPI integration

---

api/app/views/mno_enterprise/jpi/v1/organizations/members.json.jbuilder

Should be tested alongwith OPALSUP-286

[OPAL-531] Users not added to the Company's member list immediately after adding to the list

---

api/lib/mno_enterprise/concerns/controllers/webhook/o_auth_controller.rb
api/spec/controllers/mno_enterprise/webhook/o_auth_controller_spec.rb
core/config/initializers/00_tenant_config_schema.rb

Improve redirection workflows on `OAuthController`
*Summary*
- Capture redirect path on `sync` and `disconnect`
- Add option to skip redirection speedbump

[MARLIN-142] Improve connection redirections

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb

Provide clients asking for the marketplace apps and products a sorted
list of data. This does away with then need for client side sorting.

[OPALSUP-280] Sort marketplace server-side

---

core/config/initializers/00_tenant_config_schema.rb
core/config/locales/templates/dashboard/organization/en.yml

Seee maestrano/mno-enterprise-angular#543

[OPALSUP-281] Add billing currency flag

---

.travis.yml
api/app/controllers/mno_enterprise/jpi/v1/admin/invoices_controller.rb
common_mnoe_dependencies.rb
core/app/pdf/mno_enterprise/invoice_pdf.rb
core/lib/accountingjs_serializer.rb
core/lib/mno_enterprise/platform_adapters/nex_adapter.rb
core/mno-enterprise-core.gemspec

* Update Omniauth, nex_cli and webmock
* Bump Travis rubies
* Fix currency_as_string deprecation warnings (somehow still showing Travis)

 [MARLIN-243] Update Omniauth and other gems

---

api/app/views/mno_enterprise/jpi/v1/admin/organizations/show.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
core/lib/mno_enterprise/testing_support/factories/sync_status.rb

@ouranos I'm not sure entirely sure which branch I should be making a PR too, but becasue the other sync status stuff is made on 4.0, I'm putting this one on 4.0.

[MNOE-1286] Sync status for apps

---

api/config/routes.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/organizations_controller.rb
api/lib/mno_enterprise/support_search.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
api/spec/lib/mno_enterprise/support_search_spec.rb

From 803ac90 to a78e195, everything else is part of: https://github.com/maestrano/mno-enterprise/pull/751
Edit by @ouranos: [comparison link](https://github.com/maestrano/mno-enterprise/pull/788/files/f3cc135b0da36f1cc2fa81be8cd2f1f8921d398a..a78e195b78fce258a466fe15706761ae591dacca)

[MARLIN-377] Expand search functionality

---

api/app/views/mno_enterprise/jpi/v1/admin/products/_product.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/subscriptions/_subscription.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/products/_product.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/subscriptions/_subscription.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb
core/app/models/mno_enterprise/product.rb

- Expose Product#multi_instantiable in admin product jbuilder partial.
- Remove client specific code from product partials.

[OPALSUP-344] Multi instantiable products

---

api/config/routes.rb
api/spec/routing/mno_enterprise/jpi/v2/users_controller_routing_spec.rb

[MACAW-14] Update user

---

api/app/views/mno_enterprise/jpi/v1/admin/organizations/_organization.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/subscriptions/_subscription.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/organizations/_organization.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/organizations/show.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
core/config/locales/templates/components/en.yml
core/config/locales/templates/dashboard/marketplace/en.yml
core/config/locales/templates/dashboard/organization/en.yml
core/lib/mno_enterprise/concerns/models/organization.rb
core/lib/mno_enterprise/testing_support/factories/organizations.rb
core/lib/mno_enterprise/testing_support/organizations_shared_helpers.rb

Add in_arrears attribute to MnoEnterprise::Organization and to included
fields in admin organizations controller #show action.

[MNOE-1296] Account details

---

api/spec/requests/devise/authentication_spec.rb
core/lib/devise/strategies/remote_authenticatable.rb

Update devise remote authenticatable strategy so that failed login
attempts can be tracked.

[MNOE-1307] Failed login attempts

---

api/app/views/mno_enterprise/jpi/v1/admin/impac/dashboards/_kpi.json.jbuilder

[MARLIN-511] dashboards not showing

---

api/spec/spec_helper.rb
core/lib/mno_enterprise/mail_client.rb
core/lib/mno_enterprise/smtp_client.rb
core/spec/lib/mno_enterprise/smtp_client_spec.rb

Applying review comments from @ouranos on https://github.com/maestrano/mno-enterprise/pull/802

[MACAWSUP-53] Reflect email branding
