maestrano/mno-enterprise

core/lib/her_extension/model/parse.rb

fix the bug in "her" gem by continuing the patching.
The error is the original gem is due to the next call that does not returns the hash
that hash is then given in the inject method as first argument, and since it is nil, cause an error

fix issue with company renaming

---

rails-template/README.md
rails-template/mnoe-app-template.rb

We need sprockets (and uglifier) to be able to compile
mnoe/config.js.erb at deployment to provide env specific config to the
frontend.

Fix assets precompile: add sprockets

---

core/app/pdf/mno_enterprise/invoice_pdf.rb

I think price should be send as a hash instead of a formatted string (because some information is lost, for example $12 can be 12  USD or 12 AUD)
See PR: https://github.com/maestrano/Maestrano/pull/1594

Use price instead of price_tag

---

frontend-admin/src/app/components/mnoe-api/admin/current-user.svc.coffee
frontend-admin/src/app/components/mnoe-api/admin/users.svc.coffee
frontend-admin/src/app/components/mnoe-staffs-list/mnoe-staffs-list.coffee
frontend-admin/src/app/index.constants.coffee
frontend-admin/src/app/views/dashboard.controller.coffee
frontend-admin/src/app/views/dashboard.layout.html
frontend-admin/src/app/views/staff/create-staff-modal/create-staff.controller.coffee

- I fixed a bug stopping the page to reload when an action was done on a staff (update, delete, add).
- Sends an invitation email when a staff is added so that he connects.
- Stopped non admin "admin" to access the staff page.
- Make sure that the back-end stops staff to change admin_role.
- Brings a new staff straight away to the admin platform and not to the enterprise dashboard..

Fixed bugs in the staff page and added improvments

---

api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/users_controller_spec.rb
core/app/controllers/mno_enterprise/application_controller.rb
core/lib/mno_enterprise/core.rb
core/lib/mno_enterprise/testing_support/factories/users.rb
core/spec/controllers/mno_enterprise/application_controller_spec.rb
core/spec/controllers/mno_enterprise/i18n_spec.rb
frontend-admin/src/app/components/mnoe-api/admin/current-user.svc.coffee
frontend-admin/src/app/index.route.coffee

Same as #50 but merging to 3.1
- Make sure that the back-end stops staff to change admin_role.
- Brings a new staff straight away to the admin platform and not to the enterprise dashboard

[MNOE-106] Admin Panel Improvements

---

api/lib/mno_enterprise/concerns/controllers/pages_controller.rb
api/spec/controllers/mno_enterprise/pages_controller_spec.rb

Add-on (Applications using the connector framework) needs to transmit parameters for example /mnoe/launch/cld-9pfh?settings=true
These parameters needs to be transfered to the MnoEnterprise.router.launch_url

Transmit parameters  given to launch in the redirection

---

frontend/lib/tasks/mnoe_frontend_tasks.rake
frontend/lib/tasks/templates/font-faces.less

Since `main.less` imports `font-faces.less`, creates this file when
generating a new project.

[MNOE-117] Generate stub font-faces.less

---

core/lib/her_extension/middleware/mnoe_raise_error.rb
core/lib/mno_enterprise/core.rb
core/lib/mno_enterprise/testing_support/mno_enterprise_api_test_helper.rb
core/spec/models/mno_enterprise/base_resource_spec.rb

Handle connection and server errors
Mnoe api call will now raise `Faraday::Error::ConnectionFailed` or `Faraday::Error::ClientError` instead of returning `nil`
When the call is valid but the resource is not found it'll still return `nil` to keep the same behavior.

[MNOE-137] Add Her middleware to handle errors

---

core/lib/her_extension/model/relation.rb
core/spec/lib/her_extension/model/relation_spec.rb

If a filter is an empty array, it'll be excluded when calling
`params.to_query`, so convert it to nil instead.
eg: where('id.in' => []) => {'id.in' => nil}

[MNOE-125] Fix filtering on empty array

---

api/app/controllers/mno_enterprise/jpi/v1/admin/invoices_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/invoices_controller_spec.rb
core/app/models/mno_enterprise/tenant.rb
core/lib/mno_enterprise/testing_support/factories/tenant.rb
frontend-admin/src/app/components/mnoe-api/invoices.svc.coffee
frontend-admin/src/app/components/mnoe-api/invoices.svc.spec.coffee
frontend-admin/src/app/views/finance.controller.coffee
frontend-admin/src/app/views/finance.html

Tenant#current_billing_amount to be calculated via mnohub for performance reason (and also to
perform the currency conversion)
Admin Finance page:
- Fix invoices table amount
- Add extra finance KPIs

[MNOE-107] Fix admin finance page

---

api/app/controllers/mno_enterprise/impersonate_controller.rb
api/spec/controllers/mno_enterprise/impersonate_controller_spec.rb

Impersonate now takes a redirect_uri parameters which will be the url
the admin is redirected to when exiting impersonation.

[MNOE-149] Allow impersonate_redirect_uri

---

api/app/views/mno_enterprise/jpi/v1/current_users/show.json.jbuilder
core/app/models/mno_enterprise/user.rb
core/lib/mno_enterprise/concerns/models/intercom_user.rb
core/spec/models/mno_enterprise/user_spec.rb

Intercom need a server side generated HMAC of the user_id or email when
secure mode is enabled.
See: https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-secure-mode-on-your-web-product

[MNO-271] Add support for Intercom secure mode

---

api/spec/controllers/mno_enterprise/pages_controller_spec.rb
api/spec/controllers/mno_enterprise/webhook/o_auth_controller_spec.rb
frontend/spec/controllers/mno_enterprise/webhook/o_auth_controller_spec.rb

Freeze time when generating JWT as they are time-dependent.

Fix time-dependent specs

---

core/app/models/mno_enterprise/user.rb

` validates_uniqueness_of email ` was useless. The User Model is using the devise option validatable which  performs the uniqueness validation
http://www.rubydoc.info/github/plataformatec/devise/Devise/Models/Validatable
http://stackoverflow.com/questions/13897844/how-to-remove-duplicate-validation-errors

[MNOE-177] UI: SignUp Page: Error message displayed when email is already registered

---

frontend-admin/src/app/views/customers/create-step-1/create-step-1.html
frontend-admin/src/app/views/customers/create-step-1/create-step-1.less

[MNOE-153] Fix admin panel app selection on non-retina screens

---

api/app/controllers/mno_enterprise/jpi/v1/admin/audit_events_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb

`@users.all` is a ProxyObject, so code like  `@users.metadata if
@users.respond_to?(:metadata)` will trigger 2 requests.
By calling `#fetch` we get a relation and only fetch it once.
Before:
```
Started GET "/mnoe/jpi/v1/admin/users?limit=10&offset=0&order_by=created_at.desc" for 127.0.0.1 at 2016-11-07 20:41:31 +1100
Processing by MnoEnterprise::Jpi::V1::Admin::UsersController#index as JSON
Parameters: {"limit"=>"10", "offset"=>"0", "order_by"=>"created_at.desc"}
[localhost] GET /api/mnoe/v1/users/1235 (0.034 s)
[localhost] GET /api/mnoe/v1/users?limit=10&skip=0&sort%5B%5D=created_at.desc (0.025 s)
[localhost] GET /api/mnoe/v1/users?limit=10&skip=0&sort%5B%5D=created_at.desc (0.021 s)
[localhost] GET /api/mnoe/v1/users?limit=10&skip=0&sort%5B%5D=created_at.desc (0.020 s)
[localhost] GET …
```

[PERF] Avoid duplicated requests on admin endpoints

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/organizations_controller_spec.rb
core/app/models/mno_enterprise/user.rb
core/lib/her_extension/model/associations/association_proxy.rb

Allow to check when association is already loaded to avoid unnecessary
queries.
@alachaum @BrunoChauvet should we extract this pattern 
```ruby
if self.organizations.loaded?
self.organizations.to_a.find { |e| e.id == organization.id }
else
self.organizations.where(id: organization.id).first
end
```
to a method on the HasManyAssociation? or is it too specific?

[Perf] Add AssociationProxy#loaded?

---

core/lib/generators/mno_enterprise/install/templates/config/initializers/mno_enterprise.rb

Disable I18n when generating a new project as it won't be needed for
most projects.
This can still be enabled in the initializer if needed.

[MNOE-243] Disable I18n by default in generator

---

frontend-admin/src/app/components/mnoe-api/admin/ratings.svc.coffee
frontend-admin/src/app/components/mnoe-ratings-list/mnoe-ratings-list.coffee
frontend-admin/src/app/components/mnoe-ratings-list/mnoe-ratings-list.html
frontend-admin/src/app/index.route.coffee
frontend-admin/src/app/views/dashboard.layout.html
frontend-admin/src/app/views/ratings/ratings.html

Implement comments management in Admin Panel

---

api/config/initializers/devise.rb
api/lib/mno_enterprise/concerns/mailers/system_notification_mailer.rb
api/spec/mailer/mno_enterprise/system_notification_mailer_spec.rb
core/app/views/system_notifications/email-change.html.erb
core/app/views/system_notifications/email-change.text.erb
core/app/views/system_notifications/password-change.html.erb
core/app/views/system_notifications/password-change.text.erb
core/app/views/system_notifications/reconfirmation-instructions.html.erb
core/app/views/system_notifications/reconfirmation-instructions.text.erb
core/lib/devise/models/remote_authenticatable.rb
core/spec/lib/devise/model/remote_authenticable_spec.rb

- Notify users when password is updated.
- Sends an email to the old email when email changes.
- Sends an email to the new email when email changes.
Added specs (omg...)

[MNO-436] notify user of changes

---

api/app/views/mno_enterprise/auth/confirmations/lounge.html.haml
core/config/locales/views/auth/confirmations/en.yml

@ouranos & @alexnoox Can you have a quick look?
I tested the form and it works.

Redesigned the confirmation email page.

---

frontend-admin/src/app/components/mnoe-api/admin/current-user.svc.coffee
frontend-admin/src/app/views/dashboard.controller.coffee

@ouranos I introduced this bug only few days ago in the "admin panel improvements".
I use to have the user being only an admin role. 
```
adminRole = {admin_role: response.data.admin_role}
angular.copy(adminRole, _self.user)
```
which i didn't replaced well when I change it by user
```
user = {
name: response.data.name
surname: response.data.surname
adminRole: response.data.admin_role
email: response.data.email
}
angular.copy(user, _self.user)
```

Bugfix for displaying the staff page

---

core/config/locales/templates/components/en.yml

Added app install component locales

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/kpis_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb

@ouranos minor change to allow opts through the params for this proxied KPIs #index action. This is ultimately for passing `refresh_cache: true` to Impac! fixing IMPAC-328. Thanks

[IMPAC-328] include params opts in kpis_controller #index

---

api/config/initializers/devise.rb

We're not using ActiveRecord. This line causes ActiveRecord to be loaded
in the host app.

Devise - Do not load an ORM

---

api/lib/mno_enterprise/intercom_events_listener.rb
api/spec/lib/mno_enterprise/intercom_events_listener_spec.rb

Add the external_id field to Intercom if present.
Tag the user if a source is present.
See my comment on [MNO-512](https://maestrano.atlassian.net/browse/MNO-512) regarding the discrepancy.

[MNOE-328] Add external_id and source tagging to Intercom

---

frontend/lib/tasks/mnoe_frontend_tasks.rake

The `override_dependencies` was only run at install and upgrade.
This could cause a version rollback when multiple people were working on
the same project.

[MNOE-394] Respect yarn.lock dependencies on build

---

api/lib/mno_enterprise/concerns/controllers/pages_controller.rb

@ouranos There were errors when trying to go to the terms of use page. After looking at the logs it seems the error happens whenever a marketplace does not have apps yet. I'm not sure if this is actually an issue though as a dashboard wouldn't really be functional without any applications anyway. Please review.

Fix T&C page when no apps are present

---

core/lib/devise/hooks/lockable.rb

Patch devise lockable hook

---

core/lib/mno_enterprise/engine.rb

The mail adapter is set in a class variable of `MailAdapter`. This doesn't
work well with class reloading in development.
Use a `config.to_prepare` block to fix this issue.

[MNOE-358] Fix dev mailer

---

api/spec/controllers/mno_enterprise/auth/confirmation_controller_spec.rb
core/lib/devise/models/remote_authenticatable.rb
core/spec/lib/devise/model/remote_authenticable_spec.rb

Do not send a notification when user sets their password during
confirmation step.

[MNOE-443] Fix password change notification

---

.travis.yml
api/app/views/mno_enterprise/jpi/v1/marketplace/_app.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb
core/app/models/mno_enterprise/app.rb
core/app/models/mno_enterprise/shared_entity.rb
core/lib/mno_enterprise/concerns/models/shared_entity.rb
core/lib/mno_enterprise/testing_support/factories/apps.rb
core/spec/models/mno_enterprise/shared_entity_spec.rb

Marketplace now returns new fields and shared entities
As the `Marketplace#index` response is starting to get quite big (and the list of  apps from MnoHub as well), I've added a cache which add an extra request to MnoHub.
It adds ~50ms to the request but in most cases it avoids fetching the full App List from MnoHub (and `Her` deserialising it!).
Fetching  apps and rendering the json was quite fast, deserialising and instantiating the list of `MnoEnterprise::App` was taking the most time.
Contrary to the previous "dumb" cache (10min) this cache should always be fresh. It also allows the user browser to cache it.

Add new fields and cache to the Marketplace

---

api/app/views/mno_enterprise/jpi/v1/impac/kpis/_kpi.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/impac/widgets/_widget.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/kpis_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb

@cesar-tonnoir please review. Marked WIP as the #update & #delete actions are not validated as still working / updated.

[IMPAC-578] Create Widget KPIs

---

core/config/initializers/audit_log.rb
core/lib/devise_extension.rb

Fix double loading of rake tasks and initializers
This was defining another Engine in `core` which was loading all the `core/config/initializers` a second time.

[MNOE-27] Fix double loading

---

api/lib/mno_enterprise/concerns/controllers/webhook/o_auth_controller.rb

@ouranos changed " by ' in error message to avoid encoding issue on mnoe-admin side

[MNOE-463] - Display error message when connecting wrong Xero 

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/current_users_controller.rb

@ouranos
I spotted a little bug on the code while testing it. This should fix it.

[MNO-287] Change developer registration event description

---

core/lib/json_api_client_extension/json_api_client_orm_adapter.rb
core/spec/lib/json_api_client_extension/json_api_client_orm_adapter_spec.rb
core/spec/models/mno_enterprise/base_resource_spec.rb

Fix the `find_first` as `first` already manage the limit.
@x4d3 I've added some skeleton specs for `JsonApiClient::OrmAdapter` and `MnoEnterprise::BaseResource`, could add this the todo list?

[APIv2] Fix JsonApiClient::OrmAdapter.find_first

---

core/lib/generators/mno_enterprise/install/templates/config/application.yml
core/lib/mno_enterprise/engine.rb
rails-template/mnoe-app-template.rb

@alachaum what do you think?
I didn't use `NEX_xxx` variables here as I want this part to be platform agnostic. I can set `mailer_default_host` on the Docker entrypoint based on the `NEX_xxx` variables.
Come to think of it, `mailer_default_host|protocol` is not the most accurate name as it's used to generate link (to page and assets) in the emails we send. It's actually referring to the frontend host.
Not sure how to spec that as I can't reinitialise the app in rspec.
(WIP) I'm doing another pass on all the config to make sure nothing is missing

[MNOE-542] Parameterise ActionMailer config

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/kpis_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb

@ouranos small change to automatically create email alerts for widget KPIs on create - please review, let me know if this change can be specced? As I'm not sure it's possible with api stub jazz.

[IMPAC-623] create email alert on widget kpi create

---

api/app/views/mno_enterprise/auth/confirmations/_form.html.haml
core/lib/mno_enterprise/concerns/controllers/auth/confirmations_controller.rb
core/lib/mno_enterprise/concerns/controllers/auth/registrations_controller.rb
core/lib/mno_enterprise/testing_support/factories/users.rb
frontend/spec/controllers/mno_enterprise/auth/confirmations_controller_spec.rb

The time of agreement of TOS is stored in user[:metadata][tos_accepted_at]
It is then used in the /confirmation to create (or not) the TOS checkbox.
@ouranos

[MNOE-570] Storing the time of agreement to TOS

---

api/app/controllers/mno_enterprise/jpi/v1/admin/impac/dashboard_templates_controller.rb

Avoid using `valid?`
Most likely linked to https://github.com/maestrano/mno-enterprise/blob/69d2391  /core/app/models/mno_enterprise/base_resource.rb#L229

Fix intermittent 500 errors on dashboard templates controller

---

api/app/controllers/mno_enterprise/jpi/v1/admin/tenants_controller.rb
api/spec/requests/mnoe/jpi/v1/admin/tenants_spec.rb
core/lib/mno_enterprise/testing_support/devise_request_spec_helper.rb

Bypass Rails `deep_munge` on the Tenant config update to allow empty
array to be saved.

[MNOE-588] TenantConfig - Allow empty arrays

---

core/app/models/mno_enterprise/subscription.rb

The field `Subscription#custom_data` is currently casted as a string which ends up as a "stringified hash" on the API side.
This PR ensures that `custom_data` is not casted to a specific type, therefore allowing hashes.

Fix Subscription#custom_data type

---

core/lib/json_api_client_extension/custom_parser.rb
core/spec/models/mno_enterprise/base_resource_spec.rb

The current parser will fail if iso8601 dates have their timezone expanded. 
E.g. 
'2017-09-06T00:16:22+0000' instead of '2017-09-06T00:16:22Z'
This PR changes date parsing to use `Time.parse` instead of the stricter `Time.iso8601`

Core - Fix time parsing when timezone expanded

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/marketplace_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/products_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/marketplace_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/products_controller_spec.rb

The objective of this PR is to proxy the organization_id to the remote API to retrieve organization specific pricing information for apps and products.
The organization_id is passed to the remote backend using the `_metadata` query parameter - which impacts the view/representation of the resources.

Retrieve organization specific pricing

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscriptions_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/subscriptions_controller_spec.rb
core/app/models/mno_enterprise/subscription.rb

Scope GET calls to account manager id (current user) and verify permissions before performing controller actions.

Add account manager scoping on subscriptions

---

core/config/initializers/00_tenant_config_schema.rb

Disabled until we figure a better to migrate roles when switching the
feature flag.
The feature can still be activated by toggling the flag manually.

Hide subtenant from the config screen

---

core/lib/generators/mno_enterprise/install/templates/config/settings.yml

Not really needed, but best to have it in the settings template.
This also will make it easier to remember to update the JSON schema when merging in `4.0`

[MNOE-682] Add Intercom to Admin Panel

---

core/lib/generators/mno_enterprise/install/templates/stylesheets/variables.less
frontend/app/assets/stylesheets/mno_enterprise/variables.less
frontend/lib/tasks/mnoe_frontend_tasks.rake

Bypass gulp and build less files manually to speedup the overall theme previewer compilation.
Need to be merged after https://github.com/maestrano/mno-enterprise-angular/pull/350

[MNOE-659] Theme Previewer - Speedup Compilation

---

core/app/models/mno_enterprise/tenant_config.rb
core/spec/models/mno_enterprise/tenant_config_spec.rb

Feature flags can be marked as ReadOnly on the MnoHub side.
If a the config contains `flag_readonly: true`, the flag is considered
as readonly and marked as such in the schema.

[MNOE-665] Handle RO feature flags

---

README.md
frontend/lib/tasks/mnoe.rake

Simple task to peform all the build tasks at once:
```bash
∫ bin/rake mnoe:update_all
==> Updating the mno-enterprise gem
...
==> Updating and rebuilding the Dashboard
...
==> Updating and rebuilding the Admin Panel
...
==> Your project has been upgraded
- mno-enterprise has been updated
- mno-enterprise-angular has been updated and the frontend rebuilt
- mnoe-admin-panel has been updated and the admin-panel rebuilt
To commit your changes:
- Commit the packages:
$ git add -u *.lock
$ git commit -m "Bump packages"
- Commit the build:
$ git add public/dashboard public/admin
$ git commit -m "Rebuild frontend"
```

Add mnoe:update_all tasks to update all components

---

core/lib/mno_enterprise/platform_adapters/adapter.rb
core/lib/mno_enterprise/platform_adapters/nex_adapter.rb
core/lib/mno_enterprise/system_manager.rb
core/spec/lib/mno_enterprise/platform_adapters/nex_adapter_spec.rb

Only synchronise the assets actually needed to persist theme previewer changes across restart.
- Solve the bug that caused webstores to be stuck on old frontend versions after using the theme previewer
- Reduces the size of sync'd assets from ~400MB to ~500KB which should improve performance
This will assist in debugging/troubleshooting

[MNOE-742] Theme Previewer - Nex™ Adapter fixes

---

api/app/views/mno_enterprise/jpi/v1/impac/alerts/_alert.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/alerts_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/dashboards_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/kpis_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/alerts_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/dashboards_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb
core/app/models/mno_enterprise/alert.rb
core/lib/mno_enterprise/testing_support/factories/impac/alerts.rb
core/lib/mno_enterprise/testing_support/mno_enterprise_api_test_helper.rb

- Include Recipients in Alerts
- Use update_recipients instead of recipient_id

[MNO-695] Api v2 Dashboard missing dependency for KPI Alert Recipients

---

api/app/controllers/mno_enterprise/impersonate_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/sub_tenants_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/organizations/_organization.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/sub_tenants/_sub_tenant.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/sub_tenants/index.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/sub_tenants/show.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/users/_user.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/users/show.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/current_users/show.json.jbuilder
api/config/routes.rb
api/spec/controllers/mno_enterprise/impersonate_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/sub_tenants_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/users_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/current_users_controller_spec.rb
core/app/helpers/mno_enterprise/impersonate_helper.rb
core/app/models/mno_enterprise/sub_tenant.rb
core/app/models/mno_enterprise/user.rb
core/lib/mno_enterprise/concerns/models/organization.rb
core/lib/mno_enterprise/testing_support/mno_enterprise_api_test_helper.rb

- remove clients and account_managers dependency from sub_tenant
- remove clients dependeny from user
- introduce update_clients and update_account_managers endpoint
- replace user.mnoe_sub_tenant_id by sub_tenant_id
- add optional belong_to_subtenant and belong_to_account_manager boolean parameter depending on the sub_tenant_id and account_manager parameter

[MNOE-689] API V2 - SubTenant replace mass assignment of relation ship by diff

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/app_instances_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/app_instances_controller_spec.rb

Add a filter to retrieve only app_instances fulfilled (having a linked subscription event create/success or not being externally provisioned)
Depends on: https://github.com/maestrano/maestrano-hub/pull/805

[MNOE-779] - Filter app_instances on fulfilled_only

---

core/app/models/mno_enterprise/user.rb
core/spec/models/mno_enterprise/user_spec.rb

Fix an issue when the registration is disabled in the settings.yml and
then enabled via the MnoHub settings.
Since the routes are being build based on the User#devise_modules which
is built when loading the class, the registration route is never added.
The Devise::Models::Registerable is only adding a class method to the
user model (.new_with_session), so it's ok to always add it.

[MNOE-783] Fix registration route not being loaded

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/apps_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/apps_controller_spec.rb

The goal of this PR is to prevent inactive apps to appear on the apps selection screen in the admin panel.

[MNOE-611] Inactive Apps should not be exposed on API

---

api/spec/requests/devise/authentication_spec.rb
core/app/models/mno_enterprise/user.rb
core/lib/devise/strategies/remote_authenticatable.rb

user session is not returning either not found, either a user with password_not valid if the password is valid
Resource needed to be returned properly to be able to be updated in the devise-3.5.10/lib/devise/models/lockable.rb

[MNOE-209] Unlimited failed attempts of login

---

api/config/initializers/devise_patch.rb

The FailureApp was redirecting wihout the engine prefix (/mnoe/) which
was causing 404

[MNOE-249] Fix Devise::FailureApp routes

---

core/app/models/mno_enterprise/base_resource.rb
core/config/initializers/json_api_client.rb
core/mno-enterprise-core.gemspec

* Bump min version to 1.5.3
* Default pagination params changed in 1.5.3. See https://github.com/chingor13/json_api_client/pull/267
* Remove JsonApiClient monkey patch. See https://github.com/chingor13/json_api_client/pull/275

JsonApiClient fixes for 1.5.3

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/app/views/mno_enterprise/jpi/v1/admin/organizations/_member_or_invite.json.jbuilder
api/app/views/mno_enterprise/jpi/v1/admin/organizations/members.json.jbuilder
api/config/routes.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/organizations_controller_spec.rb
core/lib/mno_enterprise/concerns/models/organization.rb
core/lib/mno_enterprise/testing_support/shared_examples/organization_shared_examples.rb

Needed PUT #update_member and PUT #remove_member actions in admin controller for organizations
=> Move update_member logic in organization model
=> Create shared example for these two methods in a new file

[MNOE-776] Ability to update_member and remove_member from admin

---

CHANGELOG.md
api/app/views/mno_enterprise/jpi/v1/current_users/show.json.jbuilder
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/alerts_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/dashboards_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/kpis_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/impac/widgets_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/sub_tenants_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/current_users_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/dashboards_controller_spec.rb
api/spec/controllers/mno_enterprise/jpi/v1/impac/kpis_controller_spec.rb
core/app/controllers/mno_enterprise/application_controller.rb
core/app/models/mno_enterprise/impac/dashboard.rb
core/app/models/mno_enterprise/impac/kpi.rb
core/app/models/mno_enterprise/impac/widget.rb
core/lib/mno_enterprise/concerns/models/ability.rb
core/lib/mno_enterprise/concerns/models/organization.rb
core/spec/models/mno_enterprise/ability_spec.rb

- Modify `current_user` so ACL is attached to each organization
- Can pass the impersonator id to get the **impersonator's** access rights instead of the user's ones
- Add CanCan abilities to restrict the actions on Impac! controllers

Impac! permissions

---

core/lib/generators/mno_enterprise/install/templates/config/settings.yml

This add a new "Account Manager" feature flag
If the feature is enabled, a "staff" user can be assigned to customers and can only see those ones (which is the current behaviour)
If the feature is disabled, the screen to assign customers is not showing and a staff can see all customers (only difference with "admin" in this case is some screens are limited)

[MNOE-823] "Account Manager" feature flag

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb

- For the invite_member, organisation.orga_relations were not up to date with the new orga relation created from the orga invite. Then, when returning the json, this line was nil: https://github.com/manu-d/mno-enterprise/blob/4.0/api/app/views/mno_enterprise/jpi/v1/admin/base_resource/_member.json.jbuilder#L4, so we couldn't get the value on the frontend

[MNOE-776] Fix issues with invitation management

---

api/app/controllers/mno_enterprise/status_controller.rb
api/config/initializers/health_check.rb
api/spec/controllers/mno_enterprise/status_controller_spec.rb
api/spec/requests/mno_enterprise/healthcheck_spec.rb
api/spec/requests/mno_enterprise/status_spec.rb
core/lib/mno_enterprise/testing_support/request_spec_helper.rb

Fix version and health check endpoint when MnoHub is down.
If a valid session cookie was present, some before filters were dependent on MnoHub which would cause 500 errors.

[MNOE-110] Fix health check when MnoHub is down

---

api/app/views/mno_enterprise/jpi/v1/admin/tenants/show.json.jbuilder
api/spec/controllers/mno_enterprise/jpi/v1/admin/tenants_controller_spec.rb
core/lib/mno_enterprise/testing_support/factories/tenant.rb
core/spec/models/mno_enterprise/tenant_spec.rb

It allows to set the Admin Panel Settings/apps screen Read-Only when metadata.tenant_management is not "tenant"

[MNOE-821] Expose Tenant#metadata

---

api/app/controllers/mno_enterprise/jpi/v1/admin/organizations_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/organizations_controller_spec.rb

Reverts maestrano/mno-enterprise#602
Reverting as per my comment on MNOE-833. It introduces a regression and doesn't fix the original problem.

Revert "[MNOE-833] - Fix wrong entity sent back on user creation"

---

api/spec/controllers/mno_enterprise/jpi/v1/admin/app_reviews_controller_spec.rb
core/app/models/mno_enterprise/review.rb

On MnoHub side, json_api_resource needs the type of the payload to be the same as the type in the controller path, i.e 
<pre><json>
{  
"data":{  
"id":"1",
"type":"<b>comments</b>",
"attributes":{  
"description":"Great app",
"user_id":"1"
}
}
}
</pre>
needs to be sent to /api/mnoe/v2/**comments**/1

[MNOE-865] Send patch request to correct MnoHub endpoints for reviews

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/base_resource_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/sub_tenants_controller_spec.rb
core/lib/mno_enterprise/testing_support/shared_examples/jpi_v1_admin.rb

This enables us to differentiate between unauthenticated users and authenticated users which are not admin. We'll be able to handle them differently in the frontend (redirect to sign_in or customer view).
**Dependency:**
This requires a change in the admin panel to handle 403 errors.  Do not merge.
Fixed in maestrano/mnoe-admin-panel#189

[MNOE-744] Better authorisation error reporting

---

core/mno-enterprise-core.gemspec

0.9.3 breaks the dynamic locales selection.

Lock I18n to 0.9.1

---

core/app/models/mno_enterprise/dashboard.rb
core/spec/models/mno_enterprise/dashboard_spec.rb

Since ids are Integer on APIv1 and String on APIv2, this causes the
Dashboard#sorted_widgets to create on APIV2 for dashboards created and
sorted on APIv1.

[MNOE-926] Fix Dashboards backward compatibility

---

api/app/controllers/mno_enterprise/config_controller.rb
api/app/controllers/mno_enterprise/jpi/v1/admin/tenants_controller.rb
api/config/routes.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/tenants_controller_spec.rb
api/spec/requests/mnoe/jpi/v1/admin/tenants_spec.rb
core/lib/mno_enterprise/platform_adapters/adapter.rb
core/lib/mno_enterprise/platform_adapters/local_adapter.rb
core/lib/mno_enterprise/platform_adapters/nex_adapter.rb
core/lib/mno_enterprise/platform_adapters/nex_cluster_adapter.rb
core/lib/mno_enterprise/platform_adapters/test_adapter.rb
core/lib/mno_enterprise/system_manager.rb
core/mno-enterprise-core.gemspec
core/spec/lib/mno_enterprise/platform_adapters/nex_adapter_spec.rb
core/spec/lib/mno_enterprise/platform_adapters/nex_cluster_adapter_spec.rb

- When tenant config is updated, create a job on the Nex app to check the config_timestamp.
(Build fails for now. Once PR on nex_client is merged and new version is tagged, will need to update the gem)

[MNOE-970] Create Nex Job to check if restart is done

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/products_controller.rb
api/lib/mno_enterprise/concerns/controllers/jpi/v1/products_controller.rb

@BrunoChauvet @ouranos @adamaziz15 
This was changed in https://github.com/maestrano/mno-enterprise/commit/4046ddf2ca5ed55c5d22accb3fa792af6befb50c and I'm a bit confused as to why; is there a corresponding issue I could look at?  
When using #fetch_all it ignores pagination (expected behavior I assume). 
I'm a bit confused as to the purpose of the fetch_all method, because I did some testing and changing it to '.to_a' returns all the records when not given pagination parameters, but I think I'm missing something.

[MNOE-1020] Pagination broken

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/admin/subscription_events_controller.rb

Update index action of admin subscription events controller to ensure
that when there are no subscriptions present on an organization, no
subscription events are returned.

[MNOE-1127][BUG] All subscription events returned

---

api/lib/mno_enterprise/concerns/controllers/jpi/v1/teams_controller.rb

This error happens only when adding app to team or change team name, 
this PR is on the backend to  load association when team is updated
on the front end a seperate PR has been raised to mno-enterprise-angular(https://github.com/maestrano/mno-enterprise-angular/pull/481)

[MNOE-1036] Error occurs when adding members to team

---

api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb
api/spec/controllers/mno_enterprise/jpi/v1/admin/users_controller_spec.rb
core/app/models/mno_enterprise/user.rb
core/spec/models/mno_enterprise/user_spec.rb

Backporting [code from 3.3](https://github.com/maestrano/mno-enterprise/blob/master/api/app/controllers/mno_enterprise/jpi/v1/admin/users_controller.rb#L93-L96)

[MNOE-1213] Clear staff clients when updating to admin

---

core/app/models/mno_enterprise/app.rb
core/spec/models/mno_enterprise/app_spec.rb

update sanitized description to not replace for bucket name cdn-prd-maestrano

[MNOE-1266] Change of Maestrano name in the content

---

api/config/initializers/devise_patch.rb

Ported from 3.3 - #581 
The FailureApp was redirecting wihout the engine prefix (/mnoe/) which was causing 404

[OPALSUP-288][MNOE-249] Fix Devise::FailureApp routes

---

core/lib/json_api_client_extension/json_api_client_orm_adapter.rb
core/lib/mno_enterprise/testing_support/mno_enterprise_api_test_helper.rb
core/spec/lib/json_api_client_extension/json_api_client_orm_adapter_spec.rb

`#get` was raising an error when the model was not found instead of returning `nil`

[MARLINSUP-292] Fix JsonApiClient::OrgAdapter#get

---

core/config/initializers/00_tenant_config_schema.rb

Add max length constraint to invoice contact details to only allow
contact details to take up one line on invoice pdf.

[OPALSUP-343] Invoice contact details

---

api/app/views/mno_enterprise/jpi/v1/admin/impac/dashboards/_kpi.json.jbuilder

Kpi does not have a name attribute -- causes 500 error. 
Contingent on: https://github.com/maestrano/mnoe-admin-panel/pull/349

[MARLIN-511] dashboards not showing

---

common_mnoe_dependencies.rb

sqlite3 1.4 is conflicting with sqlite3_adapter which requires 1.3.x
See https://github.com/rails/rails/issues/35153

Add dependency constraint on sqlite3

---

api/config/routes.rb
api/spec/controllers/mno_enterprise/auth/sessions_controller_spec.rb
api/spec/routing/devise/sessions_routing_spec.rb
core/app/models/mno_enterprise/user.rb
core/config/initializers/00_tenant_config_schema.rb
core/lib/mno_enterprise/concerns/controllers/auth/sessions_controller.rb
core/mno-enterprise-core.gemspec
core/spec/models/mno_enterprise/user_spec.rb

https://maestrano.atlassian.net/browse/MACAWSUP-43
@ouranos | @cesar-tonnoir - I do the quick response code generation here so that the app name and id can be personalised by each enterprise. Generation and validation of otp happens in the back end via attributes and after_save callbacks. 
Hey my travis ci build is failing but I can't figure it out? Have you guys seen this error before? 
**UPDATE: This was because of sqlite3 incompatibility and was fixed recently in a different pull request.**

[MACAWSUP-43] 2fa for admin users
